# Generated by Django 3.0.8 on 2020-07-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.CharField(max_length=150)),
                ('price2', models.CharField(max_length=150)),
                ('price3', models.CharField(max_length=150)),
                ('price4', models.CharField(max_length=150)),
                ('price5', models.CharField(max_length=150)),
                ('price6', models.CharField(max_length=150)),
                ('price7', models.CharField(max_length=150)),
            ],
        ),
    ]
