# Generated by Django 3.0.8 on 2020-07-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='price4',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='price5',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='price6',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='price7',
        ),
    ]
