# Generated by Django 3.0.8 on 2020-07-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_auto_20200723_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='price2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price5',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price1',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
