# Generated by Django 3.0.8 on 2020-07-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20200724_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='price10',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price11',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price12',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price13',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price14',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price15',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price16',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price17',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price18',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price19',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price20',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price21',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price6',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price7',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price8',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='prices',
            name='price9',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
