# Generated by Django 3.0.8 on 2020-07-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_auto_20200724_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=150)),
                ('tuesday', models.CharField(max_length=150)),
                ('wednesday', models.CharField(max_length=150)),
                ('thursday', models.CharField(max_length=150)),
                ('friday', models.CharField(max_length=150)),
                ('saturday', models.CharField(max_length=150)),
                ('sunday', models.CharField(max_length=150)),
            ],
        ),
    ]
